/*
  Signal Mode Lab JS
  Isolated copy of production Utility JS for _experiments/signal-mode/ only.
  Do not use this file as production source of truth.
*/

(() => {
const KEY='the-protocol.bank.items.v12',MIG='the-protocol.bank.v12.migrated',THEME='the-protocol.theme';
const CATS=['Money','Body','Love','Work','Creative Output','Home','Visibility','Peace','Identity','Protection','Timing','Spiritual'];
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const id=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`; const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function read(k,f=[]){try{const p=JSON.parse(localStorage.getItem(k));return Array.isArray(p)?p:f}catch{return f}} function write(k,v){localStorage.setItem(k,JSON.stringify(v))} function bank(){return read(KEY)} function save(v){write(KEY,v)}
function addItem(i){let v=bank();v.unshift({id:id(),type:i.type,category:i.category||'Identity',title:i.title||'',text:i.text||'',meta:i.meta||{},createdAt:new Date().toISOString()});save(v)} function del(id){save(bank().filter(i=>i.id!==id))}
function copyText(t){return navigator.clipboard?.writeText?navigator.clipboard.writeText(t):Promise.resolve()} function label(t){return ({switch:'Switch',default:'Default',command:'Command',law:'Law',peak:'Peak',confirmation:'Receipt'})[t]||t}
function text(i){if(i.type==='command')return i.text.toUpperCase().startsWith('EXECUTE:')?i.text:`EXECUTE: ${i.text}`; if(i.type==='peak'){let m=i.meta||{};return [i.title,m.body&&`Body: ${m.body}`,m.proof&&`Proof: ${m.proof}`,m.baseline&&`Baseline: ${m.baseline}`].filter(Boolean).join('\n')} return i.text||i.title}
function row(i){return `<article class="ledger-item"><div class="ledger-item__meta"><span>${esc(label(i.type))}</span><span>${esc(i.category)}</span></div><div class="ledger-item__text">${esc(text(i)).replace(/\n/g,'<br>')}</div><div class="ledger-item__actions"><button data-copy-bank="${i.id}" type="button">Copy</button><button data-delete-bank="${i.id}" type="button">Delete</button></div></article>`}
function list(el,items,msg){if(el)el.innerHTML=items.length?items.map(row).join(''):`<p class="empty-state">${msg}</p>`}
function populateCats(){$$('[data-category-select]').forEach(s=>{let all=s.id==='bankCategoryFilter';s.innerHTML=(all?'<option value="all">All Categories</option>':'')+CATS.map(c=>`<option>${c}</option>`).join('')})}
function renderCustom(){if(!$('#custom-switches'))return;let b=bank();list($('#customSwitchList'),b.filter(i=>i.type==='switch'),'No custom switches saved yet.');list($('#customDefaultList'),b.filter(i=>i.type==='default'),'No custom defaults saved yet.');list($('#customCommandList'),b.filter(i=>i.type==='command'),'No commands saved yet.');list($('#customLawList'),b.filter(i=>i.type==='law'),'No laws saved yet.');list($('#customPeakList'),b.filter(i=>i.type==='peak'),'No peaks saved yet.');list($('#customConfirmationList'),b.filter(i=>i.type==='confirmation'),'No receipts logged yet.')}
function add(type,catSel,textSel,titleSel,meta={}){let category=$(catSel)?.value||'Identity',main=$(textSel)?.value?.trim(),title=titleSel?$(titleSel)?.value?.trim():'';if(!main&&!title)return;let m={};Object.entries(meta).forEach(([k,s])=>m[k]=$(s)?.value?.trim()||'');if(type==='command'&&main&&!main.toUpperCase().startsWith('EXECUTE:'))main=`EXECUTE: ${main}`;addItem({type,category,text:main||title,title,meta:m});[textSel,titleSel,...Object.values(meta)].filter(Boolean).forEach(s=>{let e=$(s);if(e)e.value=''});let st=$('#customStatus');if(st)st.textContent=`${label(type)} saved.`;renderCustom();renderBank()}
function renderBank(){let el=$('#bankList');if(!el)return;let type=$('#bankTypeFilter')?.value||'all',cat=$('#bankCategoryFilter')?.value||'all',q=($('#bankSearch')?.value||'').toLowerCase();let items=bank();if(type!=='all')items=items.filter(i=>i.type===type);if(cat!=='all')items=items.filter(i=>i.category===cat);if(q)items=items.filter(i=>(`${i.type} ${i.category} ${i.title} ${i.text} ${JSON.stringify(i.meta||{})}`).toLowerCase().includes(q));list(el,items,'Bank is empty. Add items from Custom.')}
function migrate(){if(localStorage.getItem(MIG))return;let out=[];let grab=(key,type)=>read(key).forEach(i=>out.push({id:id(),type,category:i.group||i.category||'Identity',title:i.name||'',text:i.text||i.name||'',meta:{},createdAt:i.createdAt||new Date().toISOString()}));grab('the-protocol.custom.switches','switch');grab('the-protocol.custom.commands','command');grab('the-protocol.custom.laws','law');grab('the-protocol.custom.confirmations','confirmation');if(out.length)save([...out,...bank()]);localStorage.setItem(MIG,'true')}
function chrome(){let t=localStorage.getItem(THEME);if(t)document.documentElement.dataset.theme=t;$$('[data-theme-toggle]').forEach(b=>b.onclick=()=>{let n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem(THEME,n)});$$('[data-mobile-menu-toggle]').forEach(b=>b.onclick=()=>{let n=$('[data-mobile-nav]');if(n)n.classList.toggle('is-open')})}
document.addEventListener('click',async e=>{let templ=e.target.closest('[data-template-target]');if(templ){let input=document.getElementById(templ.dataset.templateTarget);if(input){input.value=templ.dataset.templateValue;input.focus()}}let c=e.target.closest('[data-copy-bank]');if(c){let i=bank().find(x=>x.id===c.dataset.copyBank);if(i)await copyText(text(i))}let d=e.target.closest('[data-delete-bank]');if(d){del(d.dataset.deleteBank);renderCustom();renderBank()}});
document.addEventListener('DOMContentLoaded',()=>{chrome();populateCats();migrate();$('#addCustomSwitch')?.addEventListener('click',()=>add('switch','#customSwitchCategory',null,'#customSwitchName'));$('#addCustomDefault')?.addEventListener('click',()=>add('default','#customDefaultCategory','#customDefaultText'));$('#addCustomCommand')?.addEventListener('click',()=>add('command','#customCommandCategory','#customCommandText'));$('#addCustomLaw')?.addEventListener('click',()=>add('law','#customLawCategory','#customLawText'));$('#addCustomPeak')?.addEventListener('click',()=>add('peak','#customPeakCategory',null,'#customPeakTitle',{body:'#customPeakBody',proof:'#customPeakProof',baseline:'#customPeakBaseline'}));$('#addCustomConfirmation')?.addEventListener('click',()=>add('confirmation','#customConfirmationCategory','#customConfirmationText'));['#bankTypeFilter','#bankCategoryFilter','#bankSearch'].forEach(s=>$(s)?.addEventListener('input',renderBank));$('#exportBank')?.addEventListener('click',()=>copyText(JSON.stringify(bank(),null,2)));renderCustom();renderBank()});
})();
